version: "3.9"
services:
  geolocation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: mix run --no-halt
    volumes:
      - .:/opt/geolocation
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
